/* ========================================
 *
 * Copyright YOUR COMPANY, THE YEAR
 * All Rights Reserved
 * UNPUBLISHED, LICENSED SOFTWARE.
 *
 * CONFIDENTIAL AND PROPRIETARY INFORMATION
 * WHICH IS THE PROPERTY OF your company.
 *
 * ========================================
*/
/*******************************************************************************
* Included headers
*******************************************************************************/
#include <project.h>
#include <stdbool.h>

#define serialDebug  UART_UartPutString
//#define serialDebug  
#define serialMain  UART_UartPutString

    #define DSLEEP_LED_GREEN_OFF()  LED_DSLEEP_GREEN_Write(1)
    #define SLEEP_LED_BLUE_OFF()    LED_SLEEP_BLUE_Write(1)
    #define DSLEEP_LED_GREEN_ON()   LED_DSLEEP_GREEN_Write(0)
    #define SLEEP_LED_BLUE_ON()     LED_SLEEP_BLUE_Write(0)

/*******************************************************************************
* Variables
*******************************************************************************/
bool charNotificationEnabled = false;
uint8_t data;
bool Timerflag = false;
volatile static uint8_t phaseInterruptFlag;
volatile static uint8_t targetInterruptFlag;



/*******************************************************************************
* Function Prototypes
*******************************************************************************/
void systemPowerManagement();
void applicationRun();

/*******************************************************************************
* Function Definitions
*******************************************************************************/


/*******************************************************************************
* Function Name: StackEventHandler()
********************************************************************************
* Summary:
* Event handler function for the BLE events processing.
*
* Parameters:
* uint32 eventCode: The event to be processed
* void * eventParam: Pointer to hold the additional information associated 
*                    with an event
*
* Return:
* None
*
* Theory:
* The function is responsible for handling the events generated by the stack.
* In addition to handling general events for BLE advertisement, connection, 
* and disconnection, this function updates the negotiated MTU size on the 
* MTU Exchange Request, and also enables/disables notifications for the custom
* characteristic.
*
* Side Effects:
* None
*
*******************************************************************************/
void StackEventHandler(uint32 eventCode, void * eventParam)
{
    CYBLE_GATTS_WRITE_REQ_PARAM_T writeParam;
   
    
    switch(eventCode)
    {
        /* Stack initialized; ready for advertisement */
        case CYBLE_EVT_STACK_ON:
            UART_UartPutString("15 \r\n");
            CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
            break;
        
        /* Advertisement timed out; Restart advertisement */
        case CYBLE_EVT_GAPP_ADVERTISEMENT_START_STOP:
            if(CyBle_GetState() == CYBLE_STATE_DISCONNECTED)
            {
                CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
                 //UART_UartPutString("\n\rAdvertising stopped restarted again. ");
                UART_UartPutString("16 \r\n");
            }
            break;

        case CYBLE_EVT_GAP_DEVICE_CONNECTED:
             //UART_UartPutString("\n\rConnected. ");
            UART_UartPutString("17 \r\n");
            break;
            
        /* Device disconnected; restart advertisement */
        case CYBLE_EVT_GAP_DEVICE_DISCONNECTED:
            charNotificationEnabled = false;
            //UART_UartPutString("\n\n\rDisconnected. ");
            //UART_UartPutString("\n\rAdvertising again. ");
            UART_UartPutString("18 \r\n");
            CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
            break;

        
            
        /* Check if the Client Characteristic Configuration Descriptor is
         * written to. Notification is enabled or disabled accordingly.
         */
        case CYBLE_EVT_GATTS_WRITE_REQ:
            UART_UartPutString("19 \r\n");
            writeParam = *(CYBLE_GATTS_WRITE_REQ_PARAM_T *)eventParam;
            CyBle_GattsWriteAttributeValue(&writeParam.handleValPair, 0u,&writeParam.connHandle, CYBLE_GATT_DB_PEER_INITIATED);
            if(writeParam.handleValPair.attrHandle == 
               CYBLE_WIRELESS_RADAR_SENSOR_CUSTOM_CHARACTERISTIC_CLIENT_CHARACTERISTIC_CONFIGURATION_DESC_HANDLE)
            {
                charNotificationEnabled = writeParam.handleValPair.value.val[0];
            }
            CyBle_GattsWriteRsp(cyBle_connHandle);
            break;
            

        /* Other events that are generated by the BLE Component that
         * are not required for functioning of this design */
        /**********************************************************
        *                       General Events
        ***********************************************************/
        case CYBLE_EVT_HARDWARE_ERROR:    /* This event indicates that some internal HW error has occurred. */
            serialDebug("1 \r\n");
            break;

        case CYBLE_EVT_HCI_STATUS:
            serialDebug("2 \r\n");
            break;

        /**********************************************************
        *                       GAP Events
        ***********************************************************/
        case CYBLE_EVT_GAP_AUTH_REQ:
            serialDebug("3 \r\n");
            break;

        case CYBLE_EVT_GAP_PASSKEY_ENTRY_REQUEST:
            serialDebug("4 \r\n");
            break;

        case CYBLE_EVT_GAP_PASSKEY_DISPLAY_REQUEST:
            serialDebug("5 \r\n");
            break;

        case CYBLE_EVT_GAP_AUTH_COMPLETE:
            serialDebug("6 \r\n");

            break;
        case CYBLE_EVT_GAP_AUTH_FAILED:
            serialDebug("7 \r\n");

            break;

        case CYBLE_EVT_GAP_ENCRYPT_CHANGE:
            serialDebug("8 \r\n");
            break;

        case CYBLE_EVT_GAPC_CONNECTION_UPDATE_COMPLETE:
            serialDebug("9 \r\n");
            break;

        /**********************************************************
        *                       GATT Events
        ***********************************************************/
        case CYBLE_EVT_GATT_CONNECT_IND:
            serialDebug("10 \r\n");
            break;

        case CYBLE_EVT_GATT_DISCONNECT_IND:
            serialDebug("11 \r\n");
            break;

        case CYBLE_EVT_GATTS_XCNHG_MTU_REQ:
            serialDebug("12 \r\n");
            break;

        case CYBLE_EVT_GATTS_READ_CHAR_VAL_ACCESS_REQ:
            serialDebug("13 \r\n");
            break;

        /**********************************************************
        *                       Other Events
        ***********************************************************/
        case CYBLE_EVT_PENDING_FLASH_WRITE:
            serialDebug("14 \r\n");
            break;

        default:
            break;
    }
}


/*******************************************************************************
* Function Name: SendNotification()
********************************************************************************
* Summary:
* This function creates a notification packet and sends it.
*
* Parameters:
* None
*
* Return:
* None
*
* Theory:
* The function creates a notification packet for the custom characteristic and 
* sends it over BLE. The amount of data sent for the characteristic is equal 
* to (negotiated MTU size - 3) bytes.
*
* Side Effects:
* None
*
*******************************************************************************/
void SendNotification(void)
{
    /* Create a new notification packet */
    CYBLE_GATTS_HANDLE_VALUE_NTF_T notificationPacket;
    
    /* Update Notification packet with the data.
     * Maximum data which can be sent is equal to (Negotiated MTU - 3) bytes.
     */
    notificationPacket.attrHandle = CYBLE_WIRELESS_RADAR_SENSOR_CUSTOM_CHARACTERISTIC_CHAR_HANDLE;
    notificationPacket.value.val = (uint8 *) & data;;
    notificationPacket.value.len = 1;
    
    /* Report data to BLE component */
    CyBle_GattsNotification(cyBle_connHandle, &notificationPacket);
}

void Read_Gpio(void)
{
    uint8 TpinState,PpinState;
        TpinState=Target_Detect_Read();
        if (TpinState==0)
        {
               PpinState = Phase_Detect_Read();
               if (PpinState==0)
                 {
                   UART_UartPutString("\r\nMotion detected and target is departing\r\n");
                   data = 2;
                 }
                else
                {
                  UART_UartPutString("\r\nMotion detected and target is approaching\r\n");
                  data = 1;
                }
        }
        else
        {
          UART_UartPutString("\r\nMotion not detected\r\n"); 
          data = 0;
        }
}    


CY_ISR(phaseDetect_interruptHandler)
{
   serialDebug("IP\r\n");
    phaseInterruptFlag = 1;
    PHASE_DETECT_ClearInterrupt();
}


CY_ISR(targetDetect_interruptHandler)
{
   serialDebug("IT\r\n");
    targetInterruptFlag = 1;
    TARGET_DETECT_ClearInterrupt();
}


/*******************************************************************************
* Function Name: main()
********************************************************************************
* Summary:
* The top-level application function for the project.
*
* Parameters:
* None
*
* Return:
* None
*
* Theory:
* This is the main function for the application. It does the following -
* 1. Initializes the BLE component
* 2. Initializes a buffer from which data is sent out over BLE
* 3. Sends characteristic notification packets over BLE
*
* Side Effects:
* None
*
*******************************************************************************/
int main()
{


    /* Enable global interrupts for BLE */
    CyGlobalIntEnable; 
    
    /* Initialize components */
    CyBle_Start(StackEventHandler);
    UART_Start();
    UART_UartPutString("\x1b[2J\x1b[;H \r");
    serialDebug("\r\n GPIO Pin Testing \r\n");
    
    DSLEEP_LED_GREEN_OFF();
    SLEEP_LED_BLUE_OFF();
    
    PHASE_DETECT_INT_StartEx(phaseDetect_interruptHandler);
    
    
    TARGET_DETECT_INT_StartEx(targetDetect_interruptHandler);
    
    /* Clear screen and put a welcome message */
    UART_UartPutString("\r\nBLE Radar Puck\r\n");
    
    
    
    for(;;)
    {
        /* Single API call to service all the BLE stack events. Must be
         * called at least once in a BLE connection interval */
        CyBle_ProcessEvents();
        
        /* Routine that handles application */
        applicationRun();
        
        /* BLE power management routine */
        systemPowerManagement();
    }
}


void applicationRun()
{
        if(targetInterruptFlag)
        {
            //If there is a cahnge in target pin polarity,then check 
            // if the target pin is in high or low state to verify target presence
            //assuming that phase pin is alwasy in either high or low state,
            //irrespective of the target presence
            targetInterruptFlag = 0;
            phaseInterruptFlag = 1;
        }
        
        if(phaseInterruptFlag){
            phaseInterruptFlag = 0;
            if(!PHASE_DETECT_Read())
            {
                if(TARGET_DETECT_Read())
                {
                    data = 0;
                    //Target is invalid
                    serialMain("III \r\n");
                    SendNotification();
                }
                else
                { 
                    data = 1;
                    serialMain("APPROACHING \r\n");
                    SendNotification();
                }
            }
            else
            {
                if(TARGET_DETECT_Read())
                {
                    data = 0;
                    //Target is invalid
                    serialMain("III \r\n");
                    SendNotification();
                }
                else
                { 
                    data = 2;
                    serialMain("DEPARTING \r\n");
                    SendNotification();
                }
            }
        }
       
}


void systemPowerManagement()
{
        static uint8 toggleTimeout = 0;
        CYBLE_BLESS_STATE_T blessState;
        uint8 intrStatus;
    
        /* Configure BLESS in Deep-Sleep mode */
        CyBle_EnterLPM(CYBLE_BLESS_DEEPSLEEP);
        
        /* Prevent interrupts while entering system low power modes */
        intrStatus = CyEnterCriticalSection();
        
        /* Get the current state of BLESS block */
        blessState = CyBle_GetBleSsState();
        
        /* If BLESS is in Deep-Sleep mode or the XTAL oscillator is turning on, 
         * then PSoC 4 BLE can enter Deep-Sleep mode (1.3uA current consumption) */
        if(blessState == CYBLE_BLESS_STATE_ECO_ON || 
            blessState == CYBLE_BLESS_STATE_DEEPSLEEP)
        {
            //If the green lED is prominantly glowing, then 
            //it means device is in deep sleep most of the time
            DSLEEP_LED_GREEN_ON();
            SLEEP_LED_BLUE_OFF();
            CySysPmDeepSleep();
        }
        else if(blessState != CYBLE_BLESS_STATE_EVENT_CLOSE)
        {
            //If the Blue lED is prominantly glowing, then 
            //it means device is in sleep mode most of the time
            DSLEEP_LED_GREEN_OFF();
            SLEEP_LED_BLUE_ON();;
            //serialDebug("Going into sleep\r\n");
            /* If BLESS is active, then configure PSoC 4 BLE system in 
             * Sleep mode (~1.6mA current consumption) */
            CySysPmSleep();
            //serialDebug("Exiting  sleep\r\n");
        }
        else
        {
            /* Keep trying to enter either Sleep or Deep-Sleep mode */    
        }
        
        DSLEEP_LED_GREEN_OFF();
        SLEEP_LED_BLUE_OFF();
        CyExitCriticalSection(intrStatus);
        
       
}

/* [] END OF FILE */
